### ISSUE TITLE
Premises for a given inference rule are not commutative

### ISSUE THREAD

**Issue by Jmw150** [raghav198/pamplemousse#4]
For inference rules, the order of the premises should not matter, as these are just a list of conditions.

For example the following code leads to valid output.
```
B

1. A -> B   prem;
2. A        prem;
3. B        mp 1, 2;
```
```
1. (A -> B) prem []     ✓                                                                                
2. A prem []    ✓                                                                                        
3. B mp [1, 2]  ✓                                                                                        
{(A -> B), A} |- B
```

But, when the arguments are switched the inference is no longer considered valid.
```
B

1. A -> B   prem;
2. A        prem;
3. B        mp 2, 1;
```
```
1. (A -> B) prem []     ✓                                                                                
2. A prem []    ✓                                                                                        
3. B mp [2, 1]  ✗                                                                                        
Error: A is not an implication! 
```

**Comment by raghav198** [comment]
This behavior is documented here: https://github.com/raghav198/proof-mouse?tab=readme-ov-file#inference-rules-reference. While it is a design choice, I'd be open to considering an argument otherwise. Currently, my reasoning against implementing it is that it makes error messages much harder to understand (for example, in the `mp` case how do you know which rule the student mistakenly identified as the implication?)

**Comment by Jmw150** [comment]
Sure, it makes the error message code small. But the proof system allows a subset of correct proofs without this feature.

**Comment by raghav198** [comment]
> Sure, it makes the error message code small. But the proof system allows a subset of correct proofs without this feature.

Fair enough; feel free to make a PR to that effect!
